### ISSUE TITLE
cannot set height for row

### ISSUE THREAD

**Issue by NguyenTheSon** [linways/table-to-excel#11]
I cannot set height for row
Can You help me?

**Comment by rohithb** [comment]
Currently, row height is not supported in table-to-excel. However, it is supported in exceljs. So it will not be difficult to add row hight support to this library. I will try to work on it this weekend.

**Comment by NguyenTheSon** [comment]
thank you very much! In cell, Can you different text formats format font-size and type text? because I have many different format text in cell

**Comment by RoseEnd** [comment]
hi, is  row height supported now?

**Comment by rohithb** [comment]
Added option to specify row height. 
Now you can specify row height using `data-height` in the `<tr>` tag.
Check release [v1.0.3](https://github.com/linways/table-to-excel/releases/tag/v1.0.3)

**Comment by rohithb** [comment]
> thank you very much! In cell, Can you different text formats format font-size and type text? because I have many different format text in cell
Refer #16
