### ISSUE TITLE
Column for Currency

### ISSUE THREAD

**Issue by sunnykoundal** [linways/table-to-excel#17]
I am try to add currency in excel sheet but there is no option I could found for that. Can you add that option like other data-t="c" - for currency.

**Comment by rohithb** [comment]
Currency formatting  is already available. You can use `data-num-fmt` to specify the number format. For example: 
`<td data-t="n" data-num-fmt="$ 0.00">2210.00</td>` 
Check [this example](https://codepen.io/rohithb/pen/YdjVbb)

You can use any excel cell format strings inside `data-num-fmt` like
`$#,##0.00_);[Red]($#,##0.00)`,  `_($* #,##0.00_);_($* (#,##0.00);_($* "-"??_);_(@_)`  etc.

**Comment by sunnykoundal** [comment]
Hi Rohit
Thanks for replying me!

It solves my issue. 
Thanks
