### ISSUE TITLE
Date Datatype

### ISSUE THREAD

**Issue by meet1997** [linways/table-to-excel#18]
After giving data type as date, the value exported to excel is the value of 1 day before.

**Comment by rohithb** [comment]
Could you please reproduce the issue on [jsfiddle](https://jsfiddle.net/)/[codepen](https://codepen.io/) and post its link here?

**Comment by meet1997** [comment]
Link to jsfiddle: [Click here](https://jsfiddle.net/3rsm64no)
I get output like this:
![Screenshot](https://user-images.githubusercontent.com/25399006/57207149-f67d1880-6fe8-11e9-9098-2fd00e2588b0.png)

Here, I get the date of 1 day before with some time like 6:30 p.m.

**Comment by rohithb** [comment]
This issue is fixed. 
This was caused by not handling the timezone properly while creating a new JavaScript Date object.
Please update to [v1.0.4](https://github.com/linways/table-to-excel/releases/tag/v1.0.4) for the fix.

**Comment by meet1997** [comment]
Thanks a lot!!  :)
