### ISSUE TITLE
Exporting Tables with Pagination

### ISSUE THREAD

**Issue by Markseemus** [linways/table-to-excel#28]
Can this library export tables with pagination?

**Comment by rohithb** [comment]
No. It will only export HTML tables present in the DOM. Currently, it does not have an option to append table to an existing sheet. 
If you have a lot of data to be exported, I won't recommend using this library. Instead, create the excel file at the server and send it to the client. (if your back end is in JavaScript you can use [exceljs/exceljs](https://github.com/exceljs/exceljs) )

xlsx is a compressed file, so if you have large amount of data you can save a lot of bandwidth and the entire process will be much faster
