### ISSUE TITLE
"Cannot merge already merged cells"

### ISSUE THREAD

**Issue by gavinhungry** [linways/table-to-excel#7]
If I attempt to convert a table with multiple rows that contain `colspan` cells, I get an error:

    Cannot merge already merged cells

Here's an example on CodePen (you can see the error in the browser console):
https://codepen.io/anon/pen/dwKOmr

This previously worked (prior to `v1.0.0`).

**Comment by rohithb** [comment]
I missed to handle some conditions while merging.
Merging is handled differently in ExcelJS.
Working on the fix

**Comment by gavinhungry** [comment]
@rohithb,

Thanks! Your fix works for me.
